export type IMETADATA_KEY = "$METADATA";
export type IINJECTABLE_KEY = "$KEY";

export const METADATA_KEY: IMETADATA_KEY = "$METADATA";
export const INJECTABLE_KEY: IINJECTABLE_KEY = "$KEY";
export const CONTROLLER_KEY = "$CONTROLLER_KEY";

export const HTTP_CONTROLLER_KEY = "$HTTP_CONTROLLER";
export const WS_CONTROLLER_KEY = "$WS_CONTROLLER";

export const CONTROLLER_METHOD_PARAMS_KEY: "$CONTROLLER_METHOD_PARAM_KEY" =
  "$CONTROLLER_METHOD_PARAM_KEY";
